version: '3'
services:
  test_init_sync:
    build: .
    volumes:
      - ../../:/source:ro
      - ../test_home:/home/timgreen
      - ../test_hcm_sync.sh:/test_hcm_sync.sh:ro
    command:
      - /test_hcm_sync.sh
