version: '3'
services:
  debian: &template
    build:
      context: .
      dockerfile: Dockerfile-debian
    volumes:
      - ../../:/source:ro
      - ../test_home:/home/timgreen
      - ../test_hcm_sync.sh:/test_hcm_sync.sh:ro
    command:
      - /test_hcm_sync.sh
  arch:
    <<: *template
    build:
      context: .
      dockerfile: Dockerfile-arch
