version: '3'
services:
  debian: &template
    build:
      context: .
      dockerfile: Dockerfile-debian
    volumes:
      - &v_source
        ../../:/source:ro
      - &v_script
        ../test_hcm_sync.sh:/test_hcm_sync.sh:ro
      - ../test_home/debian:/home/timgreen
    command:
      - /test_hcm_sync.sh
  arch:
    <<: *template
    build:
      context: .
      dockerfile: Dockerfile-arch
    volumes:
      - *v_source
      - *v_script
      - ../test_home/arch:/home/timgreen
